### PR TITLE
Make cursor in pointer when tab button is active

### PR DESCRIPTION
**Pull request by KabbAmine**
As the title said, its visually better.

### CODE REVIEW

**Comment by jerone** [comment]
Thanks for taking time to contribute; how small it is. :+1: 

Aldo I do agree that a `cursor: pointer;` looks better, I'm going to leave this up to the default theme to simulate how every other tab looks like. It took me a lot of effort to make this package part of the tab-bar (without errors), instead of just adding a button before and after the tab-bar. This way the buttons look exactly like the other tabs in the tab-bar.

Apparently the default theme's don't use a `cursor: pointer;`. I would suggest sending a PR to Atom [One light UI ](https://github.com/atom/one-light-ui) and [One dark UI ](https://github.com/atom/one-dark-ui) theme's.

**Comment by KabbAmine** [comment]
Sure, the decision is yours anyway :smiley:

Personally, I don't see the need to send a PR to Atom One themes, a `cursor: pointer` on the tabs will not be very elegant, the idea was to have it just on the new-tab button.

Thanks for your plugin :+1:

**Comment by jerone** [comment]
You can always use your `styles.less` in the ~atom directory for simple things like this:

```
.tab.new-tab {
    cursor: pointer;
}
```

**Comment by KabbAmine** [comment]
I'll do it, thanks for the tip.

**Pull request closed without merging**
